### ISSUE TITLE
gdb not working for iOS 12.1.1 uncover jalibreak.

### ISSUE THREAD

**Issue by Mr007jd** [swigger/gdb-ios#7]
**gdb not working for iOS 12.1.1 uncover jalibreak.**

**result:**
iPhone:~ root# ./gdb 
-sh: ./gdb: Bad CPU type in executable

**Comment by swigger** [comment]
This project is just a proof-of-concept. It has been proven that gdb can be ported to jailbroken IOS. However, since debugserver is more effecient on IOS, I am not mantaining this project. Back to your issue, It's because the built binary is 32 bits and you need a 64bit binary which is not ported yet.

**Comment by Mr007jd** [comment]
Thank  for Reply.

**Comment by swigger** [comment]
Sorry， my project is 64bits, I forgot that because I didn't maintain it for a long time. However, you got "bad cpu" error , that is uncommon, might because arm64/arm64e? But I think arm64e is compatilble with arm64. Also, executable in /var/root directory may not be runable, but that should cause a "cannot execute binary file" error.

You can run file ./gdb to get more information.

**Comment by Mr007jd** [comment]
still same error running from other directory.

can you suggested anything of  *"gdb"* for ios 12.1.1 uncover
jailbreak working.

or any other resources which would work for me.
